services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "IPA_2026_S3"


  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    depends_on:
      - mongo
      - web
    networks:
      - app-net
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: rabbitmq

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    networks:
      - app-net
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
      DB_NAME: "IPA_2026_S3"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "admin"
      RABBITMQ_PASS: "rabbitmq"
      PYTHONUNBUFFERED: 1

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - app-net
    env_file:
      - .env
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017"
      DB_NAME: "IPA_2026_S3"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "admin"
      RABBITMQ_PASS: "rabbitmq"
      PYTHONUNBUFFERED: 1

volumes:
  mongo-data:

networks:
  app-net:
